#!/usr/bin/lua

-- Generic WSAPI FastCGI launcher, extracts application to launch
-- from SCRIPT_FILENAME/PATH_TRANSLATED, each application (defined
-- by its script entry point) gets an isolated Lua VM; sequential
-- requests to the same application go to the same VM

pcall(require,"luarocks.require")

local common = require "wsapi.common"
local fastcgi = require "wsapi.fastcgi"

fastcgi.run(common.wsapi_loader_isolated)
