#!/usr/bin/lua

pcall(require, "luarocks.require")
require "lfs"
require "wsapi.cgi"

local arg_filename = (...)

local function splitpath(filename)
  local path, file = string.match(filename, "^(.*[/\\])([^/\\]*)$")
  if not path then path, file = "", filename end
  local start_path, colon = string.sub(path, 1, 1), string.sub(path, 2, 2)
  if not (start_path == "/" or start_path == "." or colon == ":" or start_path == "\\") then
    path = "./" .. path
  end
  return path, file
end

local function splitext(filename)
  local modname, ext = string.match(filename, "^(.+)%.([^%.]+)$")
  if not modname then modname, ext = filename, "" end
  return modname, ext
end

local function find_file(filename)
  local mode, err = lfs.attributes(filename, "mode")
  if not mode then error({ type = 404, message = err }) end
  local path, file, modname, ext
  if mode == "directory" then
    path, modname = splitpath(filename)
    path = path .. "/" .. modname
    file = modname .. ".lua"
    ext = "lua"
  else
    path, file = splitpath(filename)
    modname, ext = splitext(file)
  end
  return path, file, modname, ext
end

function send404(message)
  return function (wsapi_env)
    local function res()
      coroutine.yield(string.format([[
        <html>
        <head><title>Resource not Found</title></head>
        <body>
        <p>The specified resource could not be found on the server.
        The full error message follows:</p>
<pre>
%s
</pre>
        </body>
        </html>
      ]], tostring(message)))
    end
    return 404, { ["Content-Type"] = "text/html" }, coroutine.wrap(res)
  end
end

function send500(message)
  return function (wsapi_env)
    local function res()
      coroutine.yield(string.format([[
        <html>
        <head><title>Error in Application</title></head>
        <body>
        <p>There was an error in the specified application.
        The full error message follows:</p>
<pre>
%s
</pre>
        </body>
        </html>
      ]], tostring(message)))
    end
    return 500, { ["Content-Type"] = "text/html" }, coroutine.wrap(res)
  end
end

local function get_runner(mod)
  if type(mod) == "table" and mod.run then
    return mod.run
  else
    return mod
  end
end

local function adjust_for_iis(filename, wsapi_env)
  local script_name, ext = wsapi_env.SCRIPT_NAME:match("([^/\\%.]+)%.([^%.]+)$")
  if script_name then
    local path = filename:match("^(.+)" .. script_name .. "%." .. ext .. "[/\\]")
    if path then return path .. script_name .. "." .. ext else return filename end
  else
    return filename
  end
end

local function app_loader(wsapi_env)
  local filename = arg_filename or wsapi_env.PATH_TRANSLATED
  if filename == "" then filename = wsapi_env.SCRIPT_FILENAME end
  if filename == "" then
    return send500("The server didn't provide a filename")(wsapi_env)
  end
  filename = adjust_for_iis(filename, wsapi_env)
  local ok, path, file, modname, ext = pcall(find_file, filename)
  if not ok then
    if type(path) == table then
        return send404(path.message)(wsapi_env)
    else
        return send500(path)(wsapi_env)
    end
  end
  lfs.chdir(path)
  local ok, mod = pcall(require, modname)
  if ok then
    if wsapi_env.PATH_INFO:match(modname .. "%." .. ext) then
      wsapi_env.PATH_INFO = wsapi_env.PATH_INFO:match(modname .. "%." .. ext .. "(.*)$")
      if wsapi_env.PATH_INFO == "" then wsapi_env.PATH_INFO = "/" end 
    end
    return get_runner(mod)(wsapi_env)
  else
    if type(mod) == "table" then
      return send404(mod.message)(wsapi_env)
    else
      return send500(mod)(wsapi_env)
    end
  end
end 

wsapi.cgi.run(app_loader)
